# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: c3793289f79ef008c3de184daa1f181e1f1e38a8d51e050f8a79b84aa30c32d1fcb3fdac2810eeaa842505bfc0e5519573b1b8f08572c2be6a316fa007b3c219

test:
  secret_key_base: 6950bca16c0e0a8e94ca3a6851b7f0daa50fe94aa95b0c07be7ddda4e692316dbaf79888dd3980c420945794e417cafaf8d452592e911625e21e5a3777ab3ce9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
